import type { LevelSpec } from '../levelSpec';
import { fill, stitch } from '../mapTools';
import { fact, tip } from '../types';
import { HALL_GATE, PIPE_BLOCKS, PIPE_BRIDGE, PIPE_END, PIPE_GARDEN, PIPE_STAIRS, PIRANHA_ARENA } from './chunks';

/** World 4 · Tool Pipes (2023–2024). Models learn to call tools, and text learns to give them orders. */

const START = [
  '                        ',
  '          ?*?           ',
  '                        ',
  '    QQQ       VV        ',
  '  S               e     ',
  '########################',
  '########################',
];

const INJECTION_FACTS = [
  fact(
    'Prompt injection hides instructions in text a model reads, so it obeys the attacker instead of the app. Simon Willison named and popularized the term in September 2022.',
    'promptInjection',
  ),
  fact('In February 2023, researchers showed "indirect" prompt injection: instructions planted in web pages or documents that a model later reads.', 'indirectInjection'),
];

export const WORLD_4: LevelSpec[] = [
  // ---------------------------------------------------------------- GPT path
  {
    id: 'gpt-4-1',
    label: '4-1',
    world: 4,
    name: 'Plugin Pipes',
    theme: 'pipes',
    toward: { name: 'GPT-4 + tools' },
    recipeKind: 'focus',
    recipe: { tools: 0.6, web: 0.4 },
    blockToken: 'tools',
    power: 'tool',
    moments: ['emDash'],
    headline: 'intro',
    intro: {
      title: 'World 4-1 · Plugin Pipes',
      date: '2023 · Training toward tool use',
      lines: [
        fact(
          'March 2023: OpenAI announces ChatGPT plugins, including web browsing and a code interpreter. In June, function calling comes to the API: the model can ask your code to run a tool.',
          'plugins',
          'functionCalling',
        ),
        tip('Grab the tool flower and press the power button (S / ↓, or ✦ on touch) to fire function calls.'),
        tip('Injection piranhas hide in the pipes. They will not come out while you stand right beside them.'),
      ],
    },
    outro: {
      title: 'You learned to use tools',
      date: 'Jun 2023 · function calling',
      lines: INJECTION_FACTS,
    },
    map: stitch(
      fill(START, { Q: 'u', V: 'w' }),
      fill(PIPE_GARDEN, { Q: 'u', V: 'w' }),
      fill(PIPE_BLOCKS, { Q: 'u', V: 'w' }),
      fill(PIPE_BRIDGE, { Q: 'w', V: 'u', Y: 'u' }),
      fill(PIPE_STAIRS, { Q: 'u', V: 'w' }),
      fill(PIPE_END, { Q: 'u' }),
    ),
  },
  {
    id: 'gpt-4-2',
    label: '4-2',
    world: 4,
    name: '128K Pipeline',
    theme: 'pipes',
    toward: { name: 'GPT-4 Turbo', paramsLabel: '128K context' },
    recipeKind: 'focus',
    recipe: { books: 0.4, web: 0.3, tools: 0.3 },
    blockToken: 'books',
    power: 'tool',
    ability: { jump: 1.06 },
    hypes: ['gptStore'],
    moments: ['emDash'],
    zones: [{ from: 96, to: 150, moment: 'winterLaziness' }],
    headline: 'intro',
    intro: {
      title: 'World 4-2 · 128K Pipeline',
      date: 'Nov 2023 · Training toward GPT-4 Turbo',
      lines: [
        fact('At OpenAI’s first DevDay, on November 6, 2023, GPT-4 Turbo arrives with a 128K context window, along with GPTs: custom versions of ChatGPT.', 'devday', 'introducingGpts'),
        tip('Longer context, longer jumps. Watch for copyright claims throwing briefs, and a December stretch that feels… lazy.'),
      ],
    },
    outro: {
      title: 'You evolved into GPT-4 Turbo',
      date: 'Nov 2023 · 128K context',
      lines: [
        fact(
          'On December 27, 2023, The New York Times sued OpenAI and Microsoft for copyright infringement, alleging that millions of its articles were used to train their models without permission.',
          'nytLawsuit',
        ),
      ],
    },
    map: stitch(
      fill(START, { Q: 'o', V: 'u' }),
      fill(PIPE_BLOCKS, { Q: 'o', V: 'w' }),
      [
        '                          ',
        '        $                 ',
        '                          ',
        '    ooo          www      ',
        '       l      e      l    ',
        '##########################',
        '##########################',
      ],
      fill(PIPE_GARDEN, { Q: 'o', V: 'u' }),
      [
        '                              ',
        '         ?U?         ooo      ',
        '                              ',
        '   www        uuu             ',
        '        e   l       e    l    ',
        '##############################',
        '##############################',
      ],
      fill(PIPE_BRIDGE, { Q: 'o', V: 'w', Y: 'u' }),
      fill(PIPE_END, { Q: 'o' }),
    ),
  },
  {
    id: 'gpt-4-3',
    label: '4-3',
    world: 4,
    name: 'Omni Keep',
    theme: 'pipes',
    toward: { name: 'GPT-4o' },
    recipeKind: 'focus',
    recipe: { audio: 0.4, images: 0.3, feedback: 0.3 },
    blockToken: 'audio',
    power: 'tool',
    boss: 'injectionPiranha',
    hypes: ['sora', 'gadgets'],
    moments: ['emDash'],
    headline: 'intro',
    intro: {
      title: 'World 4-3 · Omni Keep',
      date: 'May 2024 · Training toward GPT-4o',
      lines: [
        fact('May 13, 2024: GPT-4o ("o" for omni) takes text, audio, images and video as input, and can answer speech in as little as 232 milliseconds.', 'gpt4o'),
        tip('Two hype blocks wait on the way. The Injection Piranha waits in the keep: hit it when it pops out, with a stomp or a function call.'),
      ],
    },
    outro: {
      title: 'You evolved into GPT-4o',
      date: 'May 13, 2024 · omni',
      lines: [
        fact('An assistant that reads web pages, email and documents meets text written by anyone, and any of it can try to give orders: that is the injection problem.', 'indirectInjection'),
        INJECTION_FACTS[0],
      ],
    },
    map: stitch(
      [
        'XXXXXXXXXXXXXXXXXXXXXXXX',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '          ?*?           ',
        '                        ',
        '    mmm       vv        ',
        '  S               e     ',
        '########################',
        '########################',
      ],
      fill(PIPE_GARDEN, { Q: 'm', V: 'v' }),
      [
        '                            ',
        '       $        $           ',
        '                            ',
        '   mm      fff      vv      ',
        '        e       j       e   ',
        '############################',
        '############################',
      ],
      fill(PIPE_STAIRS, { Q: 'f', V: 'm' }),
      fill(PIPE_BLOCKS, { Q: 'v', V: 'm' }),
      HALL_GATE,
      PIRANHA_ARENA,
    ),
  },

  // ------------------------------------------------------------- Claude path
  {
    id: 'claude-4-1',
    label: '4-1',
    world: 4,
    name: 'Three Sizes',
    theme: 'pipes',
    toward: { name: 'Claude 3' },
    recipeKind: 'focus',
    recipe: { images: 0.4, books: 0.3, feedback: 0.3 },
    blockToken: 'images',
    power: 'tool',
    ability: { sizes: ['Claude 3 Haiku', 'Claude 3 Sonnet', 'Claude 3 Opus'] },
    hypes: ['gadgets'],
    intro: {
      title: 'World 4-1 · Three Sizes',
      date: 'Mar 2024 · Training toward Claude 3',
      lines: [
        fact('March 4, 2024: Anthropic launches the Claude 3 family in three sizes, in ascending order of capability: Haiku, Sonnet and Opus.', 'claude3'),
        tip('Press the power button (S / ↓, or ✦) to switch size: Haiku is quick and light, Opus is big and breaks bricks.'),
      ],
    },
    outro: {
      title: 'You evolved into Claude 3',
      date: 'Mar 4, 2024 · Haiku · Sonnet · Opus',
      lines: [fact('All three models could read images, like photos, charts and diagrams, and launched with a 200K context window.', 'claude3')],
    },
    map: stitch(
      fill(START, { Q: 'v', V: 'o' }),
      fill(PIPE_GARDEN, { Q: 'v', V: 'f' }),
      [
        '                                ',
        '      BBBBBB     $       BBB    ',
        '      BvvvvB                    ',
        '      BBBBBB       ooo          ',
        '                                ',
        '   ff       e          e    vv  ',
        '################################',
        '################################',
      ],
      fill(PIPE_BLOCKS, { Q: 'o', V: 'v' }),
      fill(PIPE_BRIDGE, { Q: 'f', V: 'v', Y: 'o' }),
      fill(PIPE_END, { Q: 'v' }),
    ),
  },
  {
    id: 'claude-4-2',
    label: '4-2',
    world: 4,
    name: 'Artifact Workshop',
    theme: 'pipes',
    toward: { name: 'Claude 3.5 Sonnet' },
    recipeKind: 'focus',
    recipe: { code: 0.6, images: 0.2, feedback: 0.2 },
    blockToken: 'code',
    power: 'tool',
    hypes: ['artifacts'],
    moment: 'goldenGate',
    intro: {
      title: 'World 4-2 · Artifact Workshop',
      date: 'Jun 2024 · Training toward Claude 3.5 Sonnet',
      lines: [
        fact('June 2024: Claude 3.5 Sonnet arrives with Artifacts: code, documents and designs that appear in a window beside the chat.', 'claude35'),
        tip('An orange ! block holds a moment from May 2024. The hype block holds Artifacts: press the power button to build platforms.'),
      ],
    },
    outro: {
      title: 'You evolved into Claude 3.5 Sonnet',
      date: 'Jun 2024 · Artifacts',
      lines: [fact('Anthropic said Claude 3.5 Sonnet outperformed Claude 3 Opus on a wide range of evaluations while running at twice its speed.', 'claude35')],
    },
    map: stitch(
      fill(START, { Q: 'c', V: 'v' }),
      [
        '                                ',
        '          !                     ',
        '                                ',
        '   ccc          ccc      ff     ',
        '        e                 e     ',
        '#######      ######      #######',
        '#######      ######      #######',
      ],
      fill(PIPE_GARDEN, { Q: 'c', V: 'f' }),
      [
        '                              ',
        '        $                     ',
        '                              ',
        '   cc          vv        cc   ',
        '        e              e      ',
        '#########       ##############',
        '#########       ##############',
      ],
      fill(PIPE_STAIRS, { Q: 'c', V: 'v' }),
      fill(PIPE_END, { Q: 'c' }),
    ),
  },
  {
    id: 'claude-4-3',
    label: '4-3',
    world: 4,
    name: 'Universal Pipes Keep',
    theme: 'pipes',
    toward: { name: 'Claude 3.5 Sonnet (new)' },
    recipeKind: 'focus',
    recipe: { tools: 0.5, agentic: 0.5 },
    blockToken: 'tools',
    power: 'tool',
    boss: 'injectionPiranha',
    hypes: ['mcp'],
    headline: 'intro',
    intro: {
      title: 'World 4-3 · Universal Pipes Keep',
      date: 'Oct–Nov 2024 · Training toward computer use',
      lines: [
        fact(
          'October 22, 2024: an upgraded Claude 3.5 Sonnet can use a computer: look at a screen, move a cursor, click and type. Anthropic said it was the first frontier model to offer this in public beta.',
          'computerUse',
        ),
        tip('The hype block holds MCP: every pipe connects. The Injection Piranha waits in the keep: hit it when it pops out.'),
      ],
    },
    outro: {
      title: 'You learned computer use and MCP',
      date: 'Oct 22, 2024 · agents and tools',
      lines: [fact('In November 2024, Anthropic open-sourced MCP, an open standard for connecting AI assistants to tools and data.', 'mcp'), ...INJECTION_FACTS],
    },
    map: stitch(
      [
        'XXXXXXXXXXXXXXXXXXXXXXXX',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '          ?*?           ',
        '                        ',
        '    uuu       aa        ',
        '  S               e     ',
        '########################',
        '########################',
      ],
      fill(PIPE_GARDEN, { Q: 'u', V: 'a' }),
      [
        '                          ',
        '        $                 ',
        '                          ',
        '   aaa         uuu        ',
        '       e     j      e     ',
        '##########################',
        '##########################',
      ],
      fill(PIPE_STAIRS, { Q: 'a', V: 'u' }),
      fill(PIPE_BLOCKS, { Q: 'u', V: 'a' }),
      HALL_GATE,
      PIRANHA_ARENA,
    ),
  },
];
