import type { LevelSpec } from '../levelSpec';
import { stitch } from '../mapTools';
import { fact, tip } from '../types';
import { SKY_GATE, TWIN_ARENA } from './arenas';

/** World 3 · Viral Skies (Nov 2022–2023). ChatGPT goes viral; the Timeline arrives. */

const TWIN_FACTS = [
  fact(
    "Within weeks of ChatGPT's launch, users traded \"DAN\" (Do Anything Now) prompts that role-played it into ignoring its rules. In Feb 2023, long chats with Bing's new chatbot, codename Sydney, turned strange, and Microsoft capped chats at 5 turns per session and 50 per day.",
    'danJailbreak',
    'bingLimits',
  ),
  fact('"The Waluigi Effect" (March 2023) argued that training a chatbot toward one character makes its opposite easier to summon.', 'waluigi'),
];

/** The Timeline's section: ledges high enough to stomp the cloud from. */
const TIMELINE_RUN = [
  '                                ',
  '                                ',
  '     T                          ',
  '           ====        ====     ',
  '                                ',
  '        ww      ww       ww     ',
  '      ====            ====      ',
  '   e          e            e    ',
  '##########    ######    ########',
  '##########    ######    ########',
];

const SKY_STAIRS = [
  '                         X            ',
  '                        XX            ',
  '                       XXX            ',
  '                      XXXX            ',
  '          f f f      XXXXX            ',
  '                    XXXXXX            ',
  '    e              XXXXXXX     F      ',
  '######################################',
  '######################################',
];

export const WORLD_3: LevelSpec[] = [
  // ---------------------------------------------------------------- GPT path
  {
    id: 'gpt-3-1',
    label: '3-1',
    world: 3,
    name: 'Launch Day Skies',
    theme: 'skies',
    toward: { name: 'ChatGPT' },
    recipeKind: 'focus',
    recipe: { feedback: 0.6, web: 0.4 },
    blockToken: 'feedback',
    power: 'viral',
    timeline: 'hype',
    moments: ['emDash'],
    setPieces: [
      { kind: 'starRain', from: 55, to: 95, every: 1.6 },
      { kind: 'toggles', period: 1.8, toast: 'So many new users! Some platforms are at capacity: wait for your color.' },
    ],
    intro: {
      title: 'World 3-1 · Launch Day Skies',
      date: 'Nov 2022 · Training toward ChatGPT',
      lines: [
        fact('OpenAI releases ChatGPT as a free research preview on November 30, 2022: a GPT-3.5 model fine-tuned for conversation with RLHF.', 'chatgptBlog'),
        tip('This step’s key ingredients: a web-trained base model and human feedback on conversations.'),
        tip('Viral stars make you invincible. The Timeline appears: a cloud of hot takes. Stomp it from a high ledge, then ride it.'),
      ],
    },
    outro: {
      title: 'You became ChatGPT',
      date: 'Nov 30, 2022 · research preview',
      lines: [
        fact('ChatGPT passed 1 million users about five days after launch.', 'chatgptMillion'),
        fact('It was trained with the same RLHF methods as InstructGPT; human AI trainers wrote example conversations, playing both the user and the assistant.', 'chatgptBlog'),
      ],
    },
    map: stitch(
      [
        '                      ',
        '        ?*?           ',
        '                      ',
        '    fff       w w     ',
        '  S                   ',
        '######################',
        '######################',
      ],
      [
        '          ff              ',
        '         ====             ',
        '                          ',
        '   ww               ww    ',
        '       ====    ====       ',
        '  e                   e   ',
        '#####              #######',
        '#####              #######',
      ],
      [
        '                              ',
        '      B?BUB        ?M?        ',
        '                              ',
        '  ff        ww         ff     ',
        '      e   e      e        e   ',
        '##############################',
        '##############################',
      ],
      [
        '       ff   ff   ff   ff      ',
        '                              ',
        '     [[[  ]]]  [[[  ]]]       ',
        '                              ',
        '  XX                     XX   ',
        '  XX                     XX   ',
        '  XX      e       e      XX   ',
        '##############################',
        '##############################',
      ],
      TIMELINE_RUN,
      SKY_STAIRS,
    ),
  },
  {
    id: 'gpt-3-2',
    label: '3-2',
    world: 3,
    name: 'Vision Keep',
    theme: 'skycastle',
    toward: { name: 'GPT-4' },
    recipeKind: 'focus',
    recipe: { web: 0.5, images: 0.3, feedback: 0.2 },
    blockToken: 'images',
    power: 'viral',
    boss: 'danSydney',
    timeline: 'backlash',
    hype: 'autogpt',
    moments: ['emDash'],
    ability: { vision: true },
    intro: {
      title: 'World 3-2 · Vision Keep',
      date: '2023 · Training toward GPT-4',
      lines: [
        fact('GPT-4 arrives on March 14, 2023, and it accepts images as well as text.', 'gpt4Blog'),
        tip('New vision: you can see hidden blocks. The glowing outlines are real in this level, and they lead to Images tokens.'),
        tip('Stomp Jailbreakers into their shells and kick them. DAN & Sydney wait in the keep: only one can be hit at a time.'),
      ],
    },
    outro: {
      title: 'You evolved into GPT-4',
      date: 'Mar 14, 2023 · multimodal',
      lines: [
        fact('OpenAI reported that GPT-4 scored around the top 10% of test takers on a simulated bar exam.', 'gpt4Blog', 'gpt4Paper'),
        fact('Image input reached ChatGPT users in September 2023.', 'gpt4v'),
        ...TWIN_FACTS,
      ],
    },
    map: stitch(
      [
        '                        ',
        '          ?*?           ',
        '                        ',
        '    www       vv        ',
        '  S               j     ',
        '########################',
        '########################',
      ],
      [
        '         vvvv               ',
        '        ::::::              ',
        '                            ',
        '     ::                     ',
        '                            ',
        '  ::                        ',
        '      ====    ====          ',
        '  e                    e    ',
        '#####              #########',
        '#####              #########',
      ],
      [
        '                          ',
        '        B$B?B      ww     ',
        '                          ',
        '                          ',
        '    j        j     j      ',
        '##########################',
        '##########################',
      ],
      TIMELINE_RUN.map((r) => r.replace(/w/g, 'v')),
      [
        '                          ',
        '          ?M?             ',
        '                          ',
        '    www          ff       ',
        '       e     j            ',
        '##########################',
        '##########################',
      ],
      SKY_GATE,
      TWIN_ARENA,
    ),
  },
  {
    id: 'gpt-3-3',
    label: '3-3',
    world: 3,
    name: 'Five Days in November',
    theme: 'storm',
    toward: { name: 'GPT-4' },
    recipeKind: 'focus',
    recipe: { feedback: 1 },
    blockToken: 'feedback',
    power: 'viral',
    storm: 'boardCrisis',
    hype: 'qstar',
    intro: {
      title: 'Storm · Five Days in November',
      date: 'Nov 17–22, 2023 · OpenAI board crisis',
      lines: [
        fact('On November 17, 2023, OpenAI’s board removes its CEO, Sam Altman, saying he was "not consistently candid" in his communications with the board.', 'boardTransition'),
        tip('The screen scrolls on its own through five days, and the conveyor ground reverses every morning. Keep up!'),
        tip('Collect 12 hearts to end the storm early.'),
      ],
    },
    outro: {
      title: 'You weathered the storm',
      date: 'Nov 2023 · five days',
      lines: [
        fact('More than 700 of OpenAI’s roughly 770 employees signed a letter threatening to leave, and many posted "OpenAI is nothing without its people".', 'boardLetter'),
        fact('Late on November 21, OpenAI announced an agreement in principle for Altman to return as CEO with a new initial board.', 'boardReturn'),
      ],
    },
    map: stitch(
      [
        '                                  ',
        '                                  ',
        '         + +                      ',
        '                                  ',
        '        ?*?           ff          ',
        '                                  ',
        '   ff          +         +        ',
        '  S        e                      ',
        '####>>>>>>>>>>>>####>>>>>>>>>>####',
        '##################################',
      ],
      [
        '                                    ',
        '             + + +                  ',
        '                                    ',
        '            =======        +        ',
        '                                    ',
        '    ff                   ff         ',
        '        e              e            ',
        '#<<<<<<<<<#     ####<<<<<<<<<#     #',
        '###########     ##############     #',
      ],
      [
        '                                    ',
        '                         +          ',
        '             +          XX          ',
        '            XX         XXX    +     ',
        '     ff    XXX        XXXX          ',
        '          XXXX  e    XXXXX    ff    ',
        '#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>#',
        '####################################',
      ],
      [
        '                                    ',
        '        +  +  +  +  +               ',
        '                                    ',
        '       ===============      ?$?     ',
        '                                    ',
        '   ff                    ff    +    ',
        '         e       e     e            ',
        '##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<##',
        '####################################',
      ],
      [
        '                                        ',
        '         +       +                      ',
        '                                        ',
        '       ====    ====                     ',
        '                                        ',
        '   ff               ff                  ',
        '          e                       F     ',
        '##>>>>>>>>>>>>>>##     #################',
        '##################     #################',
      ],
    ),
  },

  // ------------------------------------------------------------- Claude path
  {
    id: 'claude-3-1',
    label: '3-1',
    world: 3,
    name: 'The Pause Letter',
    theme: 'storm',
    toward: { name: 'Claude' },
    recipeKind: 'focus',
    recipe: { principles: 0.5, feedback: 0.5 },
    blockToken: 'principles',
    power: 'viral',
    storm: 'pauseLetter',
    intro: {
      title: 'Storm · The Pause Letter',
      date: 'Mar 2023 · a call to pause',
      lines: [
        fact('In March 2023, an open letter from the Future of Life Institute calls on AI labs to pause, for at least six months, the training of AI systems more powerful than GPT-4.', 'pauseLetter', 'pauseNews'),
        tip('A slow fog rolls in from the left. It slows you down when it catches you: keep moving toward the flag.'),
      ],
    },
    outro: {
      title: 'You made it through the fog',
      date: 'Mar 2023 · the pause debate',
      lines: [
        fact('The letter asked that any pause be public and verifiable, and that labs and independent experts use it to develop shared safety protocols.', 'pauseLetter'),
        fact('Posted on March 22, 2023, it made headlines a week later, when news outlets reported its well-known signers.', 'pauseNews'),
      ],
    },
    map: stitch(
      [
        '                        ',
        '          ?*?           ',
        '                        ',
        '     nnn     ff         ',
        '  S               e     ',
        '########################',
        '########################',
      ],
      [
        '                              ',
        '         f n f                ',
        '                              ',
        '        =======               ',
        '                              ',
        '   nn              j   ff     ',
        '########    ##################',
        '########    ##################',
      ],
      [
        '                                ',
        '             ?M?                ',
        '                                ',
        '      PP              PP        ',
        '   ff PP    nnn       PP  ff    ',
        '      PP  e      e    PP        ',
        '################################',
        '################################',
      ],
      [
        '                              ',
        '       n f n                  ',
        '                              ',
        '      B?B?B       ====        ',
        '                              ',
        '   j         e        nn      ',
        '##############     ###########',
        '##############     ###########',
      ],
      [
        '                         X            ',
        '                        XX            ',
        '                       XXX            ',
        '                      XXXX            ',
        '          n f n      XXXXX            ',
        '                    XXXXXX            ',
        '    e       j      XXXXXXX     F      ',
        '######################################',
        '######################################',
      ],
    ),
  },
  {
    id: 'claude-3-2',
    label: '3-2',
    world: 3,
    name: '100K Skies',
    theme: 'skies',
    toward: { name: 'Claude 2' },
    recipeKind: 'focus',
    recipe: { books: 0.5, code: 0.3, feedback: 0.2 },
    blockToken: 'books',
    power: 'viral',
    timeline: 'hype',
    hype: 'autogpt',
    ability: { float: 0.8 },
    intro: {
      title: 'World 3-2 · 100K Skies',
      date: '2023 · Training toward Claude 2',
      lines: [
        fact('July 2023: Claude 2 accepts up to 100K tokens in each prompt, enough for hundreds of pages of documentation or even a book.', 'claude2'),
        tip('Long context, long hang time: you float even longer here. Books stand for long documents; Code for better coding.'),
        tip('The Timeline is here too. Stomp it from a high ledge and ride the cloud.'),
      ],
    },
    outro: {
      title: 'You evolved into Claude 2',
      date: 'Jul 11, 2023 · 100K context',
      lines: [
        fact('Claude 2 scored 71.2% on the Codex HumanEval Python test, up from 56.0%, and 76.5% on the multiple-choice section of the Bar exam.', 'claude2'),
        fact('It launched with a public beta website, claude.ai, open to anyone in the US and UK.', 'claude2'),
      ],
    },
    map: stitch(
      [
        '                      ',
        '        ?*?           ',
        '                      ',
        '    ooo       c c     ',
        '  S                   ',
        '######################',
        '######################',
      ],
      [
        '            oo              ',
        '           ====             ',
        '                            ',
        '   cc                 oo    ',
        '        ====     ====       ',
        '  e                     e   ',
        '#####                #######',
        '#####                #######',
      ],
      [
        '                               ',
        '       B$B?B       ?M?         ',
        '                               ',
        '   oo        ff         cc     ',
        '      e    e        e       e  ',
        '###########     ###############',
        '###########     ###############',
      ],
      TIMELINE_RUN.map((r) => r.replace(/w/g, 'o')),
      [
        '                                  ',
        '            ooo                   ',
        '                                  ',
        '         =======         ff       ',
        '                                  ',
        '   cc                  ====       ',
        '       e                     e    ',
        '######              ##############',
        '######              ##############',
      ],
      SKY_STAIRS.map((r) => r.replace(/f/g, 'o')),
    ),
  },
  {
    id: 'claude-3-3',
    label: '3-3',
    world: 3,
    name: '200K Keep',
    theme: 'skycastle',
    toward: { name: 'Claude 2.1' },
    recipeKind: 'focus',
    recipe: { books: 0.6, feedback: 0.2, principles: 0.2 },
    blockToken: 'books',
    power: 'viral',
    boss: 'danSydney',
    timeline: 'backlash',
    ability: { float: 0.7 },
    intro: {
      title: 'World 3-3 · 200K Keep',
      date: 'Nov 2023 · Training toward Claude 2.1',
      lines: [
        fact('November 2023: Claude 2.1 doubles the context window to 200K tokens, roughly 150,000 words or over 500 pages.', 'claude21'),
        tip('Floatier still. Stomp Jailbreakers into shells and kick them. DAN & Sydney wait in the keep: only one can be hit at a time.'),
      ],
    },
    outro: {
      title: 'You evolved into Claude 2.1',
      date: 'Nov 21, 2023 · 200K context',
      lines: [fact('Anthropic reported a 2x decrease in false statements compared with Claude 2.0.', 'claude21'), ...TWIN_FACTS],
    },
    map: stitch(
      [
        '                        ',
        '          ?*?           ',
        '                        ',
        '    ooo       nn        ',
        '  S               j     ',
        '########################',
        '########################',
      ],
      [
        '          o f o             ',
        '         =======            ',
        '                            ',
        '    oo              nf      ',
        '       ====    ====         ',
        '  e                    j    ',
        '####                ########',
        '####                ########',
      ],
      [
        '                          ',
        '        B?B?B      oo     ',
        '                          ',
        '                          ',
        '    j        j     j      ',
        '##########################',
        '##########################',
      ],
      TIMELINE_RUN.map((r) => r.replace(/w/g, 'o')),
      [
        '                          ',
        '          ?M?             ',
        '                          ',
        '    ooo          nf       ',
        '       e     j            ',
        '##########################',
        '##########################',
      ],
      SKY_GATE,
      TWIN_ARENA,
    ),
  },
];
