import type { LevelSpec } from '../levelSpec';
import { fact, tip } from '../types';

/** World 1 · Pre-training Plains (2017–2020). GPT path only; Claude joins in World 2. */
export const WORLD_1: LevelSpec[] = [
  {
    id: 'gpt-1-1',
    label: '1-1',
    world: 1,
    name: 'BookCorpus Plains',
    theme: 'plains',
    toward: { name: 'GPT-1', paramsLabel: '117M params' },
    recipeKind: 'published',
    recipe: { books: 1 },
    blockToken: 'books',
    intro: {
      title: 'World 1-1 · BookCorpus Plains',
      date: '2018 · Training toward GPT-1',
      lines: [
        fact('June 2017: Google researchers introduce the Transformer in "Attention Is All You Need". You are an untrained Transformer.', 'transformer'),
        fact('OpenAI is about to pre-train you on BookCorpus, over 7,000 unpublished books. Collect the blue Books tokens.', 'gpt1'),
        tip('Stomp Spambots: junk text you do not want to learn from. Grab a Scale crystal to grow.'),
      ],
    },
    outro: {
      title: 'You evolved into GPT-1',
      date: 'June 2018 · 117M parameters',
      lines: [
        fact('Trained on BookCorpus: over 7,000 unpublished books from many genres.', 'gpt1'),
        fact('The big idea is generative pre-training: learn from unlabeled text first, then fine-tune for each task.', 'gpt1', 'gpt1Blog'),
        fact('Long, continuous book text taught the model to track context across many sentences.', 'gpt1'),
      ],
    },
    map: [
    '                                                                                                                                                                                ',
    '                                                                                                                                                                                ',
    '                                                                                                                                                                                ',
    '                                                                                                                                                                                ',
    '                      ?                                                          wwwwww          M                                                 X                            ',
    '                                                                     www                                                                          XX                            ',
    '                                                oo                                                               kk                              XXX                            ',
    '                                       oo                                          ww                                                           XXXX                            ',
    '                ?   B?BMB     oo               PP               B?B             BBBBBBBB      ?  ?  ?                   BB?BB                  XXXXX                            ',
    '                                      PP       PP     ooo ooo                                                                                 XXXXXX                            ',
    '        ooooo                PP       PP       PP                           oooo                       ooooo                      oooooo     XXXXXXX  ooo                       ',
    '   S                  e      PP       PP e  e  PP         e e                       e e             e                       e  e            XXXXXXXX              F             ',
    '#####################################################################   #########################################   ############################################################',
    '#####################################################################   #########################################   ############################################################',
    ],
  },
  {
    id: 'gpt-1-2',
    label: '1-2',
    world: 1,
    name: 'WebText Caves',
    theme: 'caves',
    toward: { name: 'GPT-2', paramsLabel: '1.5B params' },
    recipeKind: 'published',
    recipe: { web: 1 },
    blockToken: 'web',
    intro: {
      title: 'World 1-2 · WebText Caves',
      date: '2019 · Training toward GPT-2',
      lines: [
        fact('Books alone are not enough. OpenAI builds WebText: about 8 million web pages linked from Reddit posts with 3+ karma.', 'gpt2'),
        tip('Collect the green Web tokens. Reddit karma was a cheap quality filter: people had already upvoted the links.'),
      ],
    },
    outro: {
      title: 'You evolved into GPT-2',
      date: 'Feb 2019 · 1.5B parameters',
      lines: [
        fact('Trained on WebText: about 8 million web pages (40GB).', 'gpt2'),
        fact('More than ten times bigger than GPT-1, it wrote surprisingly coherent paragraphs.', 'gpt2Blog'),
        fact('OpenAI first withheld the full model over misuse concerns, then released it in stages through Nov 2019.', 'gpt2Blog', 'gpt2Release'),
      ],
    },
    map: [
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    '                                                                                                                                                                          ',
    '                                                                                                                                                                          ',
    '                  oooooo                                                                                                                                                  ',
    '                  BBBBBB                     kk                                                            M                                                              ',
    '                                                                                                                                                  X                       ',
    '                                                         wwwwww               wwww                                                               XX                       ',
    '                                        www                                          oo                                   www                   XXX                       ',
    '              ?M?                           B?B?B          XX                       XXXX            PP    ?B?B?                                XXXX                       ',
    '                              wwwwwwPP                    XXXX                                wwwww PP                          wwwwwwww      XXXXX                       ',
    '       wwwww                        PP                   XXXXXX   wwwwww                    PP      PP          wwwwwww                      XXXXXX                       ',
    '   S                e   e e         PP            e e   XXXXXXXX      e  e                  PP  ee  PP              e e                     XXXXXXX         F             ',
    '########################################   ###################################    ########################################   #############################################',
    '########################################   ###################################    ########################################   #############################################',
    ],
  },
  {
    id: 'gpt-1-3',
    label: '1-3',
    world: 1,
    name: 'Common Crawl Castle',
    theme: 'castle',
    toward: { name: 'GPT-3', paramsLabel: '175B params' },
    recipeKind: 'published',
    recipe: { web: 0.81, books: 0.16, wiki: 0.03 },
    blockToken: 'web',
    boss: 'garbage',
    intro: {
      title: 'World 1-3 · Common Crawl Castle',
      date: '2020 · Training toward GPT-3',
      lines: [
        fact("GPT-3's mix: filtered Common Crawl (60%), WebText2 (22%), two book corpora (16%), and Wikipedia (3%). Mostly web, some books, a pinch of wiki.", 'gpt3', 'commonCrawl'),
        tip('The raw internet is full of junk. At the end of this castle waits Garbage In, the boss of unfiltered data. Stomp it three times.'),
      ],
    },
    outro: {
      title: 'You evolved into GPT-3',
      date: 'May 2020 · 175B parameters',
      lines: [
        fact('Garbage in, garbage out: GPT-3 was trained on a filtered version of Common Crawl, keeping pages that resembled high-quality reference text.', 'gpt3'),
        fact('Scale unlocked few-shot learning: give a few examples in the prompt and the model picks up a new task.', 'gpt3'),
        fact('OpenAI offered GPT-3 through an API from June 2020. Developers started building on it.', 'openaiApi'),
      ],
    },
    map: [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    '                                                                                                    X                                                 ',
    '                                                                                                    X                                                 ',
    '                                                                                                    X                                                 ',
    '                                                                                M                   X                                                 ',
    '                                                                                                    X                                                 ',
    '                                                                       www                          X                                                 ',
    '                                     ww ww  oo  wo  ow                                              X                                                 ',
    '              ?M?                           XX  XX  XX                        ?B?B?                 X                                                 ',
    '                        wwwwwwwwPP                                                                                                                    ',
    '      wwwwoo                    PP                            wwwwkww                 wwwwwwoooo        ww    ww    ww                                ',
    '   S              e  e          PP                e     e e                               e  e                                  G                H    ',
    '#####################################    ##############################    ###########################################################################',
    '#####################################    ##############################    ###########################################################################',
    ],
  },
];
