import type { LevelSpec } from '../levelSpec';
import { stitch } from '../mapTools';
import { fact, tip } from '../types';
import { CASTLE_GATEHOUSE, REWARD_HACKER_ARENA } from './arenas';

/** World 2 · Alignment Hills (2021–2022). The paths split: Claude's own story starts here. */

const REWARD_HACKER_OUTRO = fact(
  'Reward hacking: a system maximizes the reward signal instead of the goal behind it, like a boat-racing agent that circled for points instead of finishing the race.',
  'faultyRewards',
  'specGaming',
);

export const WORLD_2: LevelSpec[] = [
  // ---------------------------------------------------------------- GPT path
  {
    id: 'gpt-2-1',
    label: '2-1',
    world: 2,
    name: 'GitHub Hills',
    theme: 'hills',
    toward: { name: 'Codex' },
    recipeKind: 'published',
    recipe: { code: 1 },
    blockToken: 'code',
    intro: {
      title: 'World 2-1 · GitHub Hills',
      date: '2021 · Training toward Codex',
      lines: [
        fact('OpenAI fine-tuned GPT-3 on public code from GitHub. The result, Codex, turned plain-English requests into working programs.', 'codex', 'codexBlog'),
        fact('The Codex paper trained on 159 GB of Python code from 54 million public GitHub repositories.', 'codex'),
        tip('Collect the orange Code tokens. The Web tokens on the high routes are tempting, but Codex was trained on code.'),
      ],
    },
    outro: {
      title: 'You evolved into Codex',
      date: 'Aug 2021 · Codex in the API',
      lines: [
        fact('Codex powered GitHub Copilot, an AI pair programmer, from its preview in June 2021.', 'copilot'),
        fact('The Codex paper introduced HumanEval: 164 hand-written programming problems, each checked by unit tests.', 'codex'),
        fact('OpenAI opened Codex to developers through its API in August 2021.', 'codexBlog'),
      ],
    },
    map: stitch(
      [
        '                      ',
        '           ?c?        ',
        '                      ',
        '     ccc              ',
        '  S              e    ',
        '######################',
        '######################',
      ],
      [
        '          www           ',
        '                        ',
        '       B?BMB            ',
        '                        ',
        '                        ',
        '     cc      e   cc     ',
        '   ##################   ',
        '   ##################   ',
        '########################',
        '########################',
      ],
      [
        '   ccc            PP      ',
        '                  PP  c   ',
        '        e         PP      ',
        '#######     ##############',
        '#######     ##############',
      ],
      [
        '                   ccc          ',
        '                                ',
        '            B?B?B               ',
        '                         X      ',
        '                        XX      ',
        '       ccc             XXX      ',
        '                      XXXX  ccc ',
        '     e    e          XXXXX      ',
        '################################',
        '################################',
      ],
      [
        '       www    www            ',
        '                             ',
        '    =======  ======          ',
        '                             ',
        '                             ',
        '   cc    cc    cc   e        ',
        '#######    ####    ##########',
        '#######    ####    ##########',
      ],
      [
        '              ?M?               ',
        '                                ',
        '                                ',
        '    cccc            PP     cc   ',
        '         e  e       PP  e       ',
        '####################PP##########',
        '################################',
      ],
      [
        '                        X            ',
        '                       XX            ',
        '                      XXX            ',
        '                     XXXX            ',
        '       c c c        XXXXX            ',
        '                   XXXXXX            ',
        '    e             XXXXXXX     F      ',
        '#####################################',
        '#####################################',
      ],
    ),
  },
  {
    id: 'gpt-2-2',
    label: '2-2',
    world: 2,
    name: 'RLHF Keep',
    theme: 'castle',
    toward: { name: 'InstructGPT', paramsLabel: '1.3B params' },
    recipeKind: 'published',
    recipe: { feedback: 1 },
    blockToken: 'feedback',
    power: 'rlhf',
    boss: 'rewardHacker',
    intro: {
      title: 'World 2-2 · RLHF Keep',
      date: '2022 · Training toward InstructGPT',
      lines: [
        fact('GPT-3 could write, but it did not reliably follow instructions. OpenAI turned to human feedback.', 'instructgptBlog'),
        fact('Labelers wrote example answers and ranked model outputs. A reward model learned their preferences, and reinforcement learning tuned the model toward them: RLHF.', 'instructgpt'),
        tip('Gold RLHF stars make you invincible and raise your Alignment. Reward orbs look like tokens, but they drain it.'),
        tip('The Reward Hacker waits in the keep. It heals by eating fake reward orbs: stomp it three times.'),
      ],
    },
    outro: {
      title: 'You evolved into InstructGPT',
      date: 'Jan 2022 · 1.3B parameters',
      lines: [
        fact('Labelers preferred answers from the 1.3B InstructGPT over the 175B GPT-3, a model more than 100 times larger.', 'instructgptBlog', 'instructgpt'),
        fact('RLHF grew out of 2017 research that trained agents from human preference comparisons.', 'humanPreferences'),
        REWARD_HACKER_OUTRO,
      ],
    },
    map: stitch(
      [
        'XXXXXXXXXXXXXXXXXXXXXXXX',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '           ?*?          ',
        '                        ',
        '     fff                ',
        '  S               e     ',
        '########################',
        '########################',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '         f r f            ',
        '                          ',
        '        XXXXXXX           ',
        '                          ',
        '   ff              ff     ',
        '          e               ',
        '#######      #############',
        '#######      #############',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                   XXXX       ',
        '                   XXXX       ',
        '                   XXXX       ',
        '                              ',
        '                              ',
        '          frf                 ',
        '                              ',
        '    B?BMB       XX       XX   ',
        '               XXX       XXX  ',
        '     r        XXXX  fff  XXXX ',
        '       e     XXXXX   e   XXXXX',
        '##############################',
        '##############################',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                            ',
        '                            ',
        '                            ',
        '                            ',
        '                            ',
        '                            ',
        '        ff                  ',
        '              ff            ',
        '       ====          ?*?    ',
        '   ff       ======= r  ff   ',
        '            e          e    ',
        '#####                #######',
        '#####                #######',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXX',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '          fff           ',
        '                        ',
        '     XX          XX     ',
        '    XXX   r      XXX    ',
        '   XXXX     e    XXXX   ',
        '########################',
        '########################',
      ],
      CASTLE_GATEHOUSE,
      REWARD_HACKER_ARENA,
    ),
  },

  // ------------------------------------------------------------- Claude path
  {
    id: 'claude-2-1',
    label: '2-1',
    world: 2,
    name: 'Constitution Hills',
    theme: 'hills',
    toward: { name: 'Constitutional AI' },
    recipeKind: 'focus',
    recipe: { principles: 0.5, feedback: 0.5 },
    blockToken: 'principles',
    power: 'rlhf',
    intro: {
      title: 'World 2-1 · Constitution Hills',
      date: '2021 → 2022 · Training toward Constitutional AI',
      lines: [
        fact('In 2021, a group of former OpenAI researchers founded Anthropic, an AI safety and research company. Claude, the brother, leaves home.', 'anthropicFounded'),
        fact("Anthropic's Constitutional AI method trains a model to critique and revise its own answers using a written list of principles: a constitution.", 'constitutionalAi'),
        fact('In the Constitutional AI paper, helpfulness came from human feedback, and harmlessness from AI feedback guided by the principles.', 'constitutionalAi'),
        tip('Collect pink Principles and gold Human Feedback in equal measure.'),
        tip('Gold RLHF stars make you invincible and raise your Alignment. Reward orbs look like tokens, but they drain it.'),
        tip('Grey ☠ tokens are shadow-library books: free to grab, but not free of consequences.'),
      ],
    },
    outro: {
      title: 'You learned Constitutional AI',
      date: 'Dec 2022 · Constitutional AI paper',
      lines: [
        fact("The method is called RL from AI Feedback (RLAIF): the model's own principle-guided judgments replaced human labels for harmlessness.", 'constitutionalAi'),
        fact("In May 2023, Anthropic published Claude's constitution, with principles drawn from sources such as the UN Universal Declaration of Human Rights.", 'claudesConstitution'),
      ],
    },
    map: stitch(
      [
        '                        ',
        '            ?*?         ',
        '                        ',
        '     nnn     ff         ',
        '  S               e     ',
        '########################',
        '########################',
      ],
      [
        '                            ',
        '        f   n   f           ',
        '                            ',
        '      ==============        ',
        '                            ',
        '                            ',
        '   n      e        n   e    ',
        '############################',
        '############################',
      ],
      [
        '                                ',
        '                 nnff           ',
        '                                ',
        '               B?BMB            ',
        '                                ',
        '                                ',
        '      rf        ########        ',
        '    ####       ##########       ',
        '    ####  e   ############    e ',
        '################################',
        '################################',
      ],
      [
        '            f  n              ',
        '                              ',
        '           =====              ',
        '                              ',
        '    nn               ff       ',
        '                              ',
        '         r      e             ',
        '#######      #######    ######',
        '#######      #######    ######',
      ],
      [
        '                 sss              ',
        '                  PP              ',
        '     n f n f      PP     r        ',
        '                  PP    nff       ',
        '           PP     PP              ',
        '    e      PP     PP   e    e     ',
        '##################################',
        '##################################',
      ],
      [
        '                   ?*?              ',
        '                                    ',
        '                                    ',
        '     ffnn      ====     nnff        ',
        '                                    ',
        '         e              e     e     ',
        '#############      #################',
        '#############      #################',
      ],
      [
        '                         X           ',
        '                        XX           ',
        '                       XXX           ',
        '                      XXXX           ',
        '        n f n        XXXXX           ',
        '                    XXXXXX           ',
        '    e       e      XXXXXXX     F     ',
        '#####################################',
        '#####################################',
      ],
    ),
  },
  {
    id: 'claude-2-2',
    label: '2-2',
    world: 2,
    name: 'Helpful, Honest, Harmless Keep',
    theme: 'castle',
    toward: { name: 'Claude' },
    recipeKind: 'focus',
    recipe: { web: 0.4, feedback: 0.3, principles: 0.3 },
    blockToken: 'feedback',
    power: 'rlhf',
    boss: 'rewardHacker',
    intro: {
      title: 'World 2-2 · Helpful, Honest, Harmless Keep',
      date: '2023 · Training toward Claude',
      lines: [
        fact('Anthropic tested its assistant, Claude, with partners such as Notion, Quora, and DuckDuckGo in a closed alpha before launch.', 'introducingClaude'),
        tip('This level targets the key ingredients of the step: a pre-trained base (Web), human feedback, and principles.'),
        tip('The Reward Hacker waits in the keep. It heals by eating fake reward orbs: stomp it three times.'),
      ],
    },
    outro: {
      title: 'You became Claude',
      date: 'Mar 14, 2023 · Claude 1',
      lines: [
        fact('Anthropic introduced Claude on March 14, 2023, the same day OpenAI released GPT-4.', 'introducingClaude', 'gpt4Blog'),
        fact("Two months later, Claude's context window grew from 9K to 100K tokens: around 75,000 words in a single prompt.", 'claude100k'),
        REWARD_HACKER_OUTRO,
      ],
    },
    map: stitch(
      [
        'XXXXXXXXXXXXXXXXXXXXXXXX',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '           w w          ',
        '          ?*??          ',
        '                        ',
        '     www                ',
        '  S               e     ',
        '########################',
        '########################',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                            ',
        '                            ',
        '                            ',
        '                            ',
        '                            ',
        '                            ',
        '          n  f  n           ',
        '           r    r           ',
        '         ==========         ',
        '   ww                 ww    ',
        '    e                   e   ',
        '######                ######',
        '######                ######',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                              ',
        '                              ',
        '                              ',
        '                              ',
        '                              ',
        '        www                   ',
        '                              ',
        '       B?BMB        nnff      ',
        '                              ',
        '                  XXXXXXXX    ',
        '    e     e     XXXXXXXXXXX   ',
        '##############################',
        '##############################',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                              ',
        '                              ',
        '                              ',
        '                              ',
        '                              ',
        '           w   f   n          ',
        '                              ',
        '            ?*?               ',
        '                              ',
        '    ww            r    ww     ',
        '             e        e       ',
        '#######    ######    #########',
        '#######    ######    #########',
      ],
      [
        'XXXXXXXXXXXXXXXXXXXXXXXX',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '         nfwn           ',
        '                        ',
        '     XX          XX     ',
        '    XXX          XXX    ',
        '   XXXX  e   r   XXXX   ',
        '########################',
        '########################',
      ],
      CASTLE_GATEHOUSE,
      REWARD_HACKER_ARENA,
    ),
  },
];
