import type { LevelSpec } from '../levelSpec';
import { fill, stitch } from '../mapTools';
import { fact, tip } from '../types';
import { GHOST_CORRIDOR, GHOST_END, GHOST_HALL, GHOST_STAIRS, HALL_GATE, KING_ARENA, PIPE_END } from './chunks';

/** World 5 · Reasoning Ghost House (Sep 2024–2025). Models learn to think; falsehoods haunt the halls. */

const START = [
  'XXXXXXXXXXXXXXXXXXXXXXXX',
  '                        ',
  '                        ',
  '                        ',
  '                        ',
  '                        ',
  '                        ',
  '                        ',
  '          ?*?           ',
  '                        ',
  '    QQQ       VV        ',
  '  S               e     ',
  '########################',
  '########################',
];

const HALLUCINATION_FACT = fact(
  'The Hallucination King is a confident falsehood. OpenAI argued in September 2025 that models hallucinate partly because training and tests reward a confident guess over "I don’t know".',
  'hallucinate',
  'hallucinationSurvey',
);

/** How many R's in strawberry? Letter blocks over the floor; the gated reward corridor above. */
const STRAWBERRY_ROOM = [
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  '                                  ',
  '                  XXXXXXXXXXXXXX  ',
  '                  D  tttttttt     ',
  '                  D  tttttttt     ',
  '             =====XXXXXXXXXXXXXX  ',
  '     1                            ',
  '     XXXXXXXXXX                   ',
  '                                  ',
  '               ====               ',
  '                                  ',
  '   t                     g      t ',
  '##################################',
  '##################################',
];

/** The Naming Maze: six labeled pipes (the sealed one wears a lid). */
const NAMING_ROOM = [
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  '                                    ',
  '                         XXXXXXXXXX ',
  '                         D  tttttt  ',
  '                         D  tttttt  ',
  '                    =====XXXXXXXXXX ',
  '                                    ',
  '                    ====            ',
  '           2                        ',
  '  5  4  1  XX 6  3                  ',
  '  PP PP PP PP PP PP                 ',
  '  PP PP PP PP PP PP     y  y        ',
  '####################################',
  '####################################',
]

/** Chart Crime: the 52.8% bar is drawn taller than the 69.1% bar. */
const CHART_ROOM = [
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  '                                  ',
  '                    XXXXXXXXXXXX  ',
  '                    D  tttttt     ',
  '                    D  tttttt     ',
  '               =====XXXXXXXXXXXX  ',
  '                                  ',
  '        1        ====             ',
  '        XX   2                    ',
  '        XX   XX                   ',
  '        XX   XX                   ',
  '   t    XX   XX           g    t  ',
  '##################################',
  '##################################',
];

/** A cave you keep getting lost in: the inviting tunnel loops back; the way on is over the top. */
const CAVE_ROOM = [
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  '                                    ',
  '                                    ',
  '             tt   aa   tt           ',
  '                                    ',
  '         ====            ====       ',
  '                                    ',
  '     ====                     ====  ',
  '                                    ',
  '          XXXXXXXXXXXXXXXXXXX       ',
  '                           7        ',
  '  8                        7        ',
  '####################################',
  '####################################',
];

const DEEPSEEK_MAP = stitch(
  [
    '                        ',
    '          ?*?           ',
    '                        ',
    '    ttt       tt        ',
    '  S                     ',
    '########################',
    '########################',
  ],
  [
    '                              ',
    '        ttt      ttt          ',
    '       =====    =====         ',
    '                              ',
    '   tt                   tt    ',
    '             e                ',
    '########    ######    ########',
    '########    ######    ########',
  ],
  [
    '                                ',
    '             ?M?                ',
    '                                ',
    '      XX              XX        ',
    '   t  XX    ttt       XX  t     ',
    '      XX  e      e    XX        ',
    '################################',
    '################################',
  ],
  [
    '                              ',
    '      tt    tt    tt          ',
    '                              ',
    '     ====  ====  ====         ',
    '                              ',
    '  e                      e    ',
    '####                 #########',
    '####                 #########',
  ],
  fill(PIPE_END, { Q: 't' }),
);

const DEEPSEEK_INTRO = [
  fact('January 20, 2025: DeepSeek releases R1, an open-weight reasoning model.', 'deepseekR1'),
  tip('Race DeepSeek-R1 to the flag. It runs at a steady pace and floats over gaps: efficient, and cheap. Rival labs are friends: this is a race, not a fight.'),
];
const DEEPSEEK_OUTRO = [
  fact('A week later its app topped Apple’s US App Store, and on January 27 Nvidia lost about $589 billion in market value in one day, a US record.', 'nvidiaDrop'),
];

export const WORLD_5: LevelSpec[] = [
  // ---------------------------------------------------------------- GPT path
  {
    id: 'gpt-5-1',
    label: '5-1',
    world: 5,
    name: 'Strawberry House',
    theme: 'ghost',
    toward: { name: 'o1-preview' },
    recipeKind: 'focus',
    recipe: { reasoning: 0.7, code: 0.3 },
    blockToken: 'reasoning',
    power: 'cape',
    hypes: ['reasoning'],
    moments: ['emDash'],
    puzzle: { kind: 'strawberry', word: 'STRAWBERRY', tokens: ['STR', 'AW', 'BERRY'], letter: 'R' },
    headline: 'intro',
    intro: {
      title: 'World 5-1 · Strawberry House',
      date: 'Sep 2024 · Training toward o1',
      lines: [
        fact('September 12, 2024: OpenAI releases o1-preview, its first model trained to spend time thinking before it answers.', 'o1'),
        tip('The reasoning cape: hold jump to glide; hold the power button to think. Thinking slows you down, reveals hidden paths, and freezes hallucination ghosts.'),
        tip('A room asks how many R’s are in "strawberry". Bump every R to open its gate.'),
      ],
    },
    outro: {
      title: 'You evolved into o1-preview',
      date: 'Sep 12, 2024 · reasoning',
      lines: [
        fact('Hallucination ghosts creep up when you stop checking. Models "hallucinate" when they state false things confidently.', 'hallucinationSurvey'),
      ],
    },
    map: stitch(
      fill(START, { Q: 't', V: 'c' }).map((r) => r.replace('?*?', '$*?')),
      fill(GHOST_HALL, { Q: 't', V: 'c' }),
      STRAWBERRY_ROOM,
      fill(GHOST_CORRIDOR, { Q: 't', V: 'c', Y: 't' }),
      fill(GHOST_STAIRS, { Q: 'c', V: 't', Y: 't' }),
      fill(GHOST_END, { Q: 't' }),
    ),
  },
  {
    id: 'gpt-5-2',
    label: '5-2',
    world: 5,
    name: 'The DeepSeek Moment',
    theme: 'storm',
    toward: { name: 'o1' },
    recipeKind: 'focus',
    recipe: { reasoning: 1 },
    blockToken: 'reasoning',
    power: 'cape',
    storm: 'deepseek',
    moments: ['emDash'],
    intro: { title: 'Storm · The DeepSeek Moment', date: 'Jan 2025 · a cheap, fast rival', lines: DEEPSEEK_INTRO },
    outro: { title: 'What a race', date: 'Jan 27, 2025 · the DeepSeek shock', lines: DEEPSEEK_OUTRO },
    map: DEEPSEEK_MAP,
  },
  {
    id: 'gpt-5-3',
    label: '5-3',
    world: 5,
    name: 'The Naming Maze',
    theme: 'ghost',
    toward: { name: 'o3' },
    recipeKind: 'focus',
    recipe: { reasoning: 0.5, tools: 0.3, images: 0.2 },
    blockToken: 'reasoning',
    power: 'cape',
    hypes: ['vibeCoding', 'ghibli'],
    moments: ['emDash'],
    puzzle: {
      kind: 'namingMaze',
      pipes: {
        '1': { label: 'o1', order: 1 },
        '2': { label: 'o2', order: null },
        '3': { label: 'GPT-4.5', order: 2 },
        '4': { label: 'GPT-4.1', order: 3 },
        '5': { label: 'o3', order: 4 },
        '6': { label: 'o4-mini', order: 4 },
      },
    },
    intro: {
      title: 'World 5-3 · The Naming Maze',
      date: 'Apr 2025 · Training toward o3',
      lines: [
        fact('April 16, 2025: OpenAI releases o3 and o4-mini, reasoning models that can use tools and think with images.', 'o3o4'),
        tip('The Naming Maze: land on the labeled pipes in release order to open the gate. Pink ★ coins are flattery: they undo your power-up.'),
      ],
    },
    outro: {
      title: 'You evolved into o3',
      date: 'Apr 16, 2025 · o3 and o4-mini',
      lines: [fact('o3 had first been announced in December 2024, when OpenAI skipped the name o2.', 'o3Announce')],
    },
    map: stitch(
      fill(START, { Q: 't', V: 'u' }),
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '           $              ',
        '                          ',
        '                          ',
        '                          ',
        '   tt   y   y   y   vv    ',
        '        e         e       ',
        '##########################',
        '##########################',
      ],
      fill(GHOST_HALL, { Q: 'u', V: 't' }),
      NAMING_ROOM,
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '          $               ',
        '                          ',
        '                          ',
        '                          ',
        '   vv        tt      uu   ',
        '       g         e        ',
        '##########################',
        '##########################',
      ],
      fill(GHOST_STAIRS, { Q: 't', V: 'v', Y: 'u' }),
      fill(GHOST_END, { Q: 't' }),
    ),
  },
  {
    id: 'gpt-5-4',
    label: '5-4',
    world: 5,
    name: 'GPT-5 Ghost Keep',
    theme: 'ghost',
    toward: { name: 'GPT-5' },
    recipeKind: 'focus',
    recipe: { reasoning: 0.4, code: 0.3, feedback: 0.3 },
    blockToken: 'reasoning',
    power: 'cape',
    boss: 'hallucinationKing',
    moments: ['emDash', 'keep4o'],
    puzzle: { kind: 'chartCrime', bars: { '1': { label: '52.8%', lies: true, fixedHeight: 2 }, '2': { label: '69.1%' } } },
    headline: 'intro',
    intro: {
      title: 'World 5-4 · GPT-5 Ghost Keep',
      date: 'Aug 2025 · Training toward GPT-5',
      lines: [
        fact('August 7, 2025: GPT-5 launches as one system: a fast model, a deeper thinking model, and a router that picks between them.', 'gpt5'),
        tip('A GPT-4o ghost follows you: keep it by reaching the end without falling. One bar chart here lies: stomp the bar that is taller than its number.'),
        tip('The Hallucination King is almost invisible. Think (hold the power button with the cape) to see it, and hit it.'),
      ],
    },
    outro: { title: 'You evolved into GPT-5', date: 'Aug 7, 2025 · one system', lines: [HALLUCINATION_FACT] },
    map: stitch(
      fill(START, { Q: 't', V: 'f' }),
      fill(GHOST_HALL, { Q: 'c', V: 't' }),
      CHART_ROOM,
      fill(GHOST_CORRIDOR, { Q: 'f', V: 't', Y: 'c' }),
      HALL_GATE,
      KING_ARENA,
    ),
  },

  // ------------------------------------------------------------- Claude path
  {
    id: 'claude-5-1',
    label: '5-1',
    world: 5,
    name: 'The DeepSeek Moment',
    theme: 'storm',
    toward: { name: 'Claude 3.5 Sonnet (new)' },
    recipeKind: 'focus',
    recipe: { reasoning: 1 },
    blockToken: 'reasoning',
    power: 'cape',
    storm: 'deepseek',
    intro: { title: 'Storm · The DeepSeek Moment', date: 'Jan 2025 · a cheap, fast rival', lines: DEEPSEEK_INTRO },
    outro: { title: 'What a race', date: 'Jan 27, 2025 · the DeepSeek shock', lines: DEEPSEEK_OUTRO },
    map: DEEPSEEK_MAP,
  },
  {
    id: 'claude-5-2',
    label: '5-2',
    world: 5,
    name: 'Extended Thinking House',
    theme: 'ghost',
    toward: { name: 'Claude 3.7 Sonnet' },
    recipeKind: 'focus',
    recipe: { reasoning: 0.5, code: 0.5 },
    blockToken: 'code',
    power: 'cape',
    hypes: ['reasoning', 'vibeCoding'],
    puzzle: { kind: 'cave' },
    intro: {
      title: 'World 5-2 · Extended Thinking House',
      date: 'Feb 2025 · Training toward Claude 3.7 Sonnet',
      lines: [
        fact(
          'February 24, 2025: Claude 3.7 Sonnet is Anthropic’s first hybrid reasoning model: it can answer instantly or think step by step, with its thinking visible. Claude Code arrives as a research preview.',
          'claude37',
        ),
        tip('The cape is extended thinking: hold jump to glide, hold the power button to think. There is a cave here that is easy to get lost in.'),
      ],
    },
    outro: {
      title: 'You evolved into Claude 3.7 Sonnet',
      date: 'Feb 24, 2025 · extended thinking',
      lines: [fact('Anthropic called Claude 3.7 Sonnet its most intelligent model to date, with particularly strong gains in coding.', 'claude37')],
    },
    map: stitch(
      fill(START, { Q: 't', V: 'c' }),
      [
        'XXXXXXXXXXXXXXXXXXXXXXXXXX',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '        $       $         ',
        '                          ',
        '                          ',
        '                          ',
        '   cc        tt      cc   ',
        '       e          g       ',
        '##########################',
        '##########################',
      ],
      fill(GHOST_HALL, { Q: 'c', V: 't' }),
      fill(CAVE_ROOM, { Q: 't' }).map((r) => r.replace(/a/g, 'c')),
      fill(GHOST_STAIRS, { Q: 't', V: 'c', Y: 'c' }),
      fill(GHOST_END, { Q: 'c' }),
    ),
  },
  {
    id: 'claude-5-3',
    label: '5-3',
    world: 5,
    name: 'Seven-Hour Halls',
    theme: 'ghost',
    toward: { name: 'Claude 4' },
    recipeKind: 'focus',
    recipe: { code: 0.5, agentic: 0.3, reasoning: 0.2 },
    blockToken: 'code',
    power: 'cape',
    intro: {
      title: 'World 5-3 · Seven-Hour Halls',
      date: 'May 2025 · Training toward Claude 4',
      lines: [
        fact('May 22, 2025: Claude Opus 4 and Claude Sonnet 4 arrive, and Claude Code becomes generally available.', 'claude4'),
        tip('A long hall: Agent tasks tokens reward staying on course.'),
      ],
    },
    outro: {
      title: 'You evolved into Claude 4',
      date: 'May 22, 2025 · Opus 4 and Sonnet 4',
      lines: [fact('Anthropic said Opus 4 could work continuously for several hours; one customer ran an open-source refactor for 7 hours.', 'claude4')],
    },
    map: stitch(
      fill(START, { Q: 'c', V: 'a' }),
      fill(GHOST_HALL, { Q: 'a', V: 'c' }),
      fill(GHOST_CORRIDOR, { Q: 'c', V: 'a', Y: 't' }),
      fill(GHOST_STAIRS, { Q: 'a', V: 'c', Y: 't' }),
      fill(GHOST_HALL, { Q: 'c', V: 'a' }),
      fill(GHOST_END, { Q: 'a' }),
    ),
  },
  {
    id: 'claude-5-4',
    label: '5-4',
    world: 5,
    name: 'The Settlement',
    theme: 'storm',
    toward: { name: 'Claude 4' },
    recipeKind: 'focus',
    recipe: { books: 1 },
    blockToken: 'books',
    power: 'cape',
    storm: 'settlement',
    intro: {
      title: 'Storm · The Settlement',
      date: 'Jun–Sep 2025 · Bartz v. Anthropic',
      lines: [
        fact(
          'June 2025: in Bartz v. Anthropic, a US judge rules that training on lawfully bought books was fair use, but sends Anthropic’s use of pirated library copies to trial.',
          'bartzOrder',
        ),
        tip('You grabbed shadow-library books back in World 2. Now the copyright claims come due: get through them to the flag.'),
      ],
    },
    outro: {
      title: 'You settled',
      date: 'Sep 2025 · $1.5 billion',
      lines: [
        fact('In September 2025, Anthropic settled with authors for $1.5 billion, about $3,000 per book for roughly 500,000 works, and agreed to destroy the pirated copies.', 'settlementPrelim'),
        fact('The settlement received final court approval on July 20, 2026.', 'settlementFinal'),
      ],
    },
    map: stitch(
      [
        '                        ',
        '          ?*?           ',
        '                        ',
        '    ooo       oo        ',
        '  S               l     ',
        '########################',
        '########################',
      ],
      [
        '                              ',
        '        ooo                   ',
        '       =====        l         ',
        '                              ',
        '   oo           l       oo    ',
        '        l                     ',
        '##############################',
        '##############################',
      ],
      [
        '                                ',
        '            ?M?                 ',
        '                                ',
        '     XX            XX           ',
        '  o  XX  l   ooo   XX  l   o    ',
        '     XX            XX           ',
        '################################',
        '################################',
      ],
      [
        '                              ',
        '     oo    oo    oo           ',
        '                              ',
        '    ====  ====  ====          ',
        '                              ',
        '  l                    l      ',
        '####                 #########',
        '####                 #########',
      ],
      fill(PIPE_END, { Q: 'o' }).map((r) => r.replace('e', 'l')),
    ),
  },
  {
    id: 'claude-5-5',
    label: '5-5',
    world: 5,
    name: 'Sonnet 4.5 Ghost Keep',
    theme: 'ghost',
    toward: { name: 'Claude Sonnet 4.5' },
    recipeKind: 'focus',
    recipe: { code: 0.4, agentic: 0.4, principles: 0.2 },
    blockToken: 'code',
    power: 'cape',
    boss: 'hallucinationKing',
    intro: {
      title: 'World 5-5 · Sonnet 4.5 Ghost Keep',
      date: 'Sep 2025 · Training toward Claude Sonnet 4.5',
      lines: [
        fact('September 29, 2025: Anthropic releases Claude Sonnet 4.5, which it called the best coding model in the world, with checkpoints in Claude Code.', 'sonnet45'),
        tip('The Hallucination King is almost invisible. Think (hold the power button with the cape) to see it, and hit it.'),
      ],
    },
    outro: {
      title: 'You evolved into Claude Sonnet 4.5',
      date: 'Sep 29, 2025',
      lines: [
        fact('Anthropic reported Sonnet 4.5 keeping focus for more than 30 hours on complex, multi-step tasks, and leading the OSWorld computer-use benchmark at 61.4%.', 'sonnet45'),
        HALLUCINATION_FACT,
      ],
    },
    map: stitch(
      fill(START, { Q: 'c', V: 'a' }),
      fill(GHOST_HALL, { Q: 'a', V: 'n' }),
      fill(GHOST_CORRIDOR, { Q: 'c', V: 'a', Y: 'n' }),
      fill(GHOST_STAIRS, { Q: 'a', V: 'c', Y: 'c' }),
      HALL_GATE,
      KING_ARENA,
    ),
  },
];
